// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz-gXgibry230sKFcHvwoAIuyTYdzRrdQ',
    appId: '1:801106561511:web:62d722a4c4ef103ec21542',
    messagingSenderId: '801106561511',
    projectId: 'pact-7331b',
    authDomain: 'pact-7331b.firebaseapp.com',
    storageBucket: 'pact-7331b.firebasestorage.app',
    measurementId: 'G-N39V66HL3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz-gXgibry230sKFcHvwoAIuyTYdzRrdQ',
    appId: '1:801106561511:android:your-android-app-id',
    messagingSenderId: '801106561511',
    projectId: 'pact-7331b',
    storageBucket: 'pact-7331b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz-gXgibry230sKFcHvwoAIuyTYdzRrdQ',
    appId: '1:801106561511:ios:your-ios-app-id',
    messagingSenderId: '801106561511',
    projectId: 'pact-7331b',
    storageBucket: 'pact-7331b.firebasestorage.app',
    iosBundleId: 'com.pact.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz-gXgibry230sKFcHvwoAIuyTYdzRrdQ',
    appId: '1:801106561511:ios:your-macos-app-id',
    messagingSenderId: '801106561511',
    projectId: 'pact-7331b',
    storageBucket: 'pact-7331b.firebasestorage.app',
    iosBundleId: 'com.pact.app',
  );
}
